# Generated by Django 4.2.3 on 2023-09-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_jual_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsmodel',
            name='alasan',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
