# Generated by Django 4.2.3 on 2023-09-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_detailsmodel_alasan'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alasan',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
